### ISSUE TITLE
Move rider status to bottom of landscape in-race screen

### ISSUE THREAD

**Issue by arthare** [arthare/btweb2#6]
Because of the unpredictability of the chrome URL bar (hard to predict whether it goes away or not), it might be good to move your current watts and hill slope to the bottom of the racing screen.  Or maybe make a tower of those stats.

Overall, the goal is to fix the issue where if your chrome URL bar doesn't go away that you have to choose between the minimap and your watts status.

**Comment by arthare4iiii** [comment]
Looks like we/I did this ages ago:
![image](https://github.com/user-attachments/assets/d8966476-52f8-486c-bc54-2519c78bf7e6)

**Comment by arthare** [comment]
You're right, arthare4iiii, we did!
